<a href="https://colab.research.google.com/github/ccapelo8/learning-pytorch/blob/main/Pytorch_by_freeCodeCamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **25. Reshaping, viewing and stacking**

In [ ]:
import torch

x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

RESHAPE, add an extra dimension

In [ ]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

Change the VIEW

In [ ]:
z = x.view(1,9)
z,x,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([1, 9]))

If we change z, x changes because they share the same memory

In [ ]:
z = x.view(1,9)
z[:,0] = 8
z,x

(tensor([[8., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([8., 2., 3., 4., 5., 6., 7., 8., 9.]))

Stack tensors on top of each other

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim = 0)
print(x_stacked)

x_stacked = torch.stack([x,x,x,x], dim = 1)
print(x_stacked)

tensor([[8., 2., 3., 4., 5., 6., 7., 8., 9.],
        [8., 2., 3., 4., 5., 6., 7., 8., 9.],
        [8., 2., 3., 4., 5., 6., 7., 8., 9.],
        [8., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([[8., 8., 8., 8.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])


There's also hstack and vstack which work a bit different.

# **26. Squeezing, unsqueezing and permuting**

Squeezing: removing all single dimensions from a target tensor

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New Shape: {x_squeezed.shape}")

Previous tensor: tensor([[8., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([8., 2., 3., 4., 5., 6., 7., 8., 9.])
New Shape: torch.Size([9])


In [ ]:
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#Adding an extra dim

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor : {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([8., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor : tensor([[8., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

Permute, rearranges dims of a target tensor in a specified order

In [ ]:
x_original = torch.rand(size = (224,224,3)) # An image (height, width and rgb)

#Permute the original tensor

x_permuted = x_original.permute(2,0,1)

print(f"Previous shape:{x_original.shape}")
print(f"New shape:{x_permuted.shape}")


Previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


#**29. Reproducibility**

Taking the random out of random

To reduce the randomness in NN and Pytorch -> random seed

Random seed: it "flavours" the randomness



In [ ]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3459, 0.3577, 0.3641, 0.6425],
        [0.1161, 0.4067, 0.9050, 0.2280],
        [0.0071, 0.1628, 0.4489, 0.3022]])
tensor([[0.5468, 0.1832, 0.4908, 0.0950],
        [0.7321, 0.4843, 0.9800, 0.4630],
        [0.8819, 0.3494, 0.4519, 0.4687]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


Setting the random seed

In [ ]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# New Section